name: 🧪 E2E Tests - Cypress

on:
  push:
    branches: [main]
  pull_request:
    types: [labeled, opened, synchronize]

jobs:
  lr-e2e-tests:
    uses: last-rev-llc/workflows/.github/workflows/e2e.yml@main
    with:
      provider: 'vercel'
      parallel-jobs: 5
      preview-max-timeout: 10000
    secrets:
      CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      SITE: ${{ secrets.SITE }}
      VERCEL_PREVIEW_DEPLOYMENT_PASSWORD: ${{ secrets.VERCEL_PREVIEW_DEPLOYMENT_PASSWORD }}
      PGP_SECRET_SIGNING_PASSPHRASE: ${{ secrets.PGP_SECRET_SIGNING_PASSPHRASE }}
